Repository dvabidonamoloka/standupstoreparser, pull requests merged in 2020-03, with the labels that each got.

#1 Make logger
  susp/utils.py
Labels: enhancement

#2 Make notification
  .gitignore
  requirements.txt
  susp/notifications.py
Labels: enhancement

#4 Add event model and refactor main script
  susp/check_events.py
  susp/db.py
  susp/event.py
Labels: enhancement

#3 Add docker-compose
  README.md
  docker-compose.dev.yml
  docker-compose.yml
Labels: documentation, enhancement

#5 Add setup manifest
  setup.py
  susp/__init__.py
Labels: enhancement

#8 Make event notifications
  susp/notifications.py
Labels: enhancement

#6 Add infinite loop to run parser script
  Dockerfile
  README.md
  docker-compose.yml
  parser_draft.ipynb
  requirements.txt
  setup.py
  susp/app.py
  susp/check_events.py
  susp/event.py
  susp/notifications.py
  susp/parser.py
  susp/utils.py
Labels: enhancement, in progress
